# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Web fanboy
tagline:          'Musings about the open web and javascript'
description:      'This is a blog about web and javascript. I reside on twitter <a href="https://www.twitter.com/swapnil_mishra">@swapnil_mishra</a> and on github <a href="https://www.github.com/swapnilmishra">@swapnilmishra</a>. Do connect if you feel like interacting.'
url:              http://lanyon.getpoole.com

author:
  name:           'Swapnil Mishra'
  url:            https://twitter.com/swapnil_mishra

paginate:         5

# Gems
gems : [jekyll-paginate]