siteTitle = "Blog by Swapnil Mishra"
siteDescr = "Frontender, <3 Open Web, amateur guitarist, almost atheist. Ex-CISCO, Oracle, Freecharge"
siteAuthor = "Swapnil Mishra"

siteTwitterUrl = "twitter.com/swapnil_mishra"
siteGithubUrl = "github.com/swapnilmishra"
siteEmailUrl = "mailto:swapmis1084@gmail.com"